version: "3"
services:
  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  backend-app:
    build:
      context: backend-app
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./backend-app:/code
    environment:
      FLASK_DEBUG: "true"
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
